clo/urls.py
from django.urls import path
from .views import (
    CloReadAllView,
    CloCreateView,
    CloUpdateView,
    CloBulkDeleteView,
    CloDuplicateView,
    CloReadAllGraphJsonResponse,
    CloReadView,
    CloLockView,
    CloUnlockView,

    KomponenCloBulkDeleteView,
    KomponenCloCreateView,
    KomponenCloGraphJsonResponse,
)


app_name = 'clo'
urlpatterns = [
    path('', CloReadAllView.as_view(), name='read-all'),
    path('<int:clo_id>/', CloReadView.as_view(), name='read'),
    path('<int:clo_id>/update/', CloUpdateView.as_view(), name='update'),
    path('create/', CloCreateView.as_view(), name='create'),
    path('duplicate/', CloDuplicateView.as_view(), name='duplicate'),
    path('bulk-delete/', CloBulkDeleteView.as_view(), name='bulk-delete'),
    path('read-all-graph/', CloReadAllGraphJsonResponse.as_view(), name='read-all-graph'),
    path('lock/', CloLockView.as_view(), name='lock'),
    path('unlock/', CloUnlockView.as_view(), name='unlock'),

    # Komponen CLO
    path('<int:clo_id>/bulk-delete/', KomponenCloBulkDeleteView.as_view(), name='komponen-clo-bulk-delete'),
    path('<int:clo_id>/create/', KomponenCloCreateView.as_view(), name='komponen-clo-create'),
    path('<int:clo_id>/komponen-graph/', KomponenCloGraphJsonResponse.as_view(), name='komponen-clo-graph')
]

laporan_cpl/urls.py
from django.urls import path
from .views import (
    GetTahunAjaranJsonResponse,
    GetSemesterJsonResponse,
    LaporanCapaianPembelajaranView,
    LaporanCapaianPembelajaranDownloadView,
    LaporanCapaianPembelajaranRawDownloadView,
    LaporanCapaianPembelajaranMahasiswaView,
    LaporanCapaianPembelajaranMahasiswaDownloadView,
    LaporanCapaianPembelajaranMahasiswaRawDownloadView,

    ListMahasiswaLaporanCPLProgrmStudiView,

    LaporanPerformanceIndicatorView,
    ListPiLaporanPiView,
    LaporanPiDownloadView,
)


app_name = 'laporan_cpl'
urlpatterns = [
    path('', LaporanCapaianPembelajaranView.as_view(), name='home'),
    path('mahasiswa-task/', ListMahasiswaLaporanCPLProgrmStudiView.as_view(), name='list-mahasiswa'),
    path('download/', LaporanCapaianPembelajaranDownloadView.as_view(), name='download'),
    path('raw-download/', LaporanCapaianPembelajaranRawDownloadView.as_view(), name='raw-download'),
    path('laporan-pi/', LaporanPerformanceIndicatorView.as_view(), name='laporan-pi'),
    path('list-result-pi/', ListPiLaporanPiView.as_view(), name='list-result-pi'),
    path('laporan-pi/download/', LaporanPiDownloadView.as_view(), name='download-laporan-pi'),

    path('<str:username>/', LaporanCapaianPembelajaranMahasiswaView.as_view(), name='laporan-mahasiswa'),
    path('<str:username>/download/', LaporanCapaianPembelajaranMahasiswaDownloadView.as_view(), name='laporan-mahasiswa-download'),
    path('<str:username>/raw-download/', LaporanCapaianPembelajaranMahasiswaRawDownloadView.as_view(), name='raw-laporan-mahasiswa-download'),
    path('formset-choices/tahun-ajaran/', GetTahunAjaranJsonResponse.as_view(), name='formset-tahun-ajaran-choices'),
    path('formset-choices/semester/', GetSemesterJsonResponse.as_view(), name='formset-semester-choices'),
]

learning_outcomes_assessment/urls.py
from django.contrib import admin
from django.urls import path, include, re_path
from .views import (
    home_view, dosen_json_response, get_task_result,
    get_admin_only_view
)
from clo.views import DuplicateCpmkLintasMkView
from django.views.static import serve 
from django.conf import settings


urlpatterns = [
    path('', home_view),
    path('admin/', admin.site.urls),
    path('accounts/', include('accounts.urls')),
    path('kurikulum/', include('kurikulum.urls')),
    path('semester/', include('semester.urls')),
    path('laporan-cpl/', include('laporan_cpl.urls')),
    path('dosen-search/', dosen_json_response, name='dosen-search'),
    path('task/', get_task_result, name='task-result'),

    # Admin only
    path('admin-only/', get_admin_only_view, name='admin-only'),
    path('admin-only/duplicate-cpmk-lintas-mk/', DuplicateCpmkLintasMkView.as_view(), name='duplicate-cpmk-lintas-mk'),

    re_path(r'^media/(?P<path>.*)$', serve,{'document_root': settings.MEDIA_ROOT}), 
    re_path(r'^static/(?P<path>.*)$', serve,{'document_root': settings.STATIC_ROOT}), 
]

laporan_cpl/models.py
from django.db import models

# Create your models here.

laporan_cpl/views.py
from django.utils import timezone
from django.core.exceptions import PermissionDenied
from django.conf import settings
from django.db.models import QuerySet
from django.shortcuts import get_object_or_404, redirect
from django.contrib.auth import get_user_model
from django.contrib.auth.mixins import LoginRequiredMixin
from django.contrib import messages
from django.http import (
    FileResponse, Http404, HttpResponse, 
    HttpRequest, JsonResponse
)
from django_q.tasks import async_task, result
from django_q.models import Task
from django.urls import reverse_lazy
from django.views.generic.base import TemplateView, View
from mata_kuliah_semester.models import PesertaMataKuliah
from learning_outcomes_assessment.forms.edit import MultiFormView
from learning_outcomes_assessment.auth.mixins import(
    MahasiswaAsPesertaMixin,
)
from pi_area.models import PerformanceIndicator
from semester.models import (
    TahunAjaranProdi,
    SemesterProdi,
)
from ilo.models import Ilo
from .forms import (
    KurikulumChoiceForm,
    TahunAjaranSemesterFormset,
    MataKuliahSemesterExcludeForm,
)
from .utils import (
    get_ilo_and_sks_from_kurikulum,
    generate_laporan_cpl_prodi_pdf,
    generate_laporan_cpl_prodi_raw,
    generate_laporan_cpl_mahasiswa_pdf,
    generate_laporan_cpl_per_mahasiswa_pdf,
    generate_laporan_cpl_per_mahasiswa_raw,
    generate_laporan_pi_pdf,
)
from .tasks import (
    process_ilo_prodi,
    process_ilo_mahasiswa,
    process_ilo_prodi_by_kurikulum,
    process_ilo_mahasiswa_by_kurikulum,
    process_pi,
    process_pi_by_kurikulum,
)


User = get_user_model()


# Create your views here.
class GetTahunAjaranJsonResponse(TemplateView):
    def get(self, request: HttpRequest, *args, **kwargs) -> HttpResponse:
        selected_kurikulum_id = request.GET.get('kurikulum_id', '')
        username = request.GET.get('username', None)
        tahun_ajaran_choices = [('', '---------')]

        # If kurikulum_id is empty str or request is not AJAX, return
        if not selected_kurikulum_id.strip() or not request.is_ajax(): 
            return JsonResponse({'choices': tahun_ajaran_choices})
        
        if request.user.role != 'm':
            if username is None:
                tahun_ajaran_prodi_qs = TahunAjaranProdi.objects.filter(
                    semesterprodi__matakuliahsemester__mk_kurikulum__kurikulum__id_neosia=selected_kurikulum_id
                ).distinct()
            else:
                tahun_ajaran_prodi_qs = TahunAjaranProdi.objects.filter(
                    semesterprodi__matakuliahsemester__mk_kurikulum__kurikulum__id_neosia=selected_kurikulum_id,
                    semesterprodi__matakuliahsemester__kelasmatakuliahsemester__pesertamatakuliah__mahasiswa__username=username
                ).distinct()
        else:
            tahun_ajaran_prodi_qs = TahunAjaranProdi.objects.filter(
                semesterprodi__matakuliahsemester__mk_kurikulum__kurikulum__id_neosia=selected_kurikulum_id,
                semesterprodi__matakuliahsemester__kelasmatakuliahsemester__pesertamatakuliah__mahasiswa=request.user
            ).distinct()
        
        tahun_ajaran_choices += [(tahun_ajaran_prodi.pk, str(tahun_ajaran_prodi.tahun_ajaran)) for tahun_ajaran_prodi in tahun_ajaran_prodi_qs]

        return JsonResponse({'choices': tahun_ajaran_choices})
    

class GetSemesterJsonResponse(TemplateView):
    def get(self, request: HttpRequest, *args, **kwargs) -> HttpResponse:
        selected_tahun_ajaran_id: str = request.GET.get('tahun_ajaran_id', '')
        username = request.GET.get('username', None)
        semester_choices = [('', '---------')]

        # If tahun_ajaran_id is empty str or request is not AJAX, return
        if not selected_tahun_ajaran_id.strip() or not request.is_ajax(): 
            return JsonResponse({'choices': semester_choices})
        
        if request.user.role != 'm':
            if username is None:
                semester_prodi_qs = SemesterProdi.objects.filter(
                    tahun_ajaran_prodi=selected_tahun_ajaran_id
                )
            else:
                semester_prodi_qs = SemesterProdi.objects.filter(
                    tahun_ajaran_prodi=selected_tahun_ajaran_id,
                    matakuliahsemester__kelasmatakuliahsemester__pesertamatakuliah__mahasiswa__username=username
                )
        else:
            semester_prodi_qs = SemesterProdi.objects.filter(
                tahun_ajaran_prodi=selected_tahun_ajaran_id,
                matakuliahsemester__kelasmatakuliahsemester__pesertamatakuliah__mahasiswa=request.user
            ).distinct()
        
        semester_choices += [(semester_prodi.pk, str(semester_prodi.semester.nama)) for semester_prodi in semester_prodi_qs]

        return JsonResponse({'choices': semester_choices})


class LaporanCapaianPembelajaranTemplateView(LoginRequiredMixin, MultiFormView):
    form_classes = {
        'kurikulum_form': KurikulumChoiceForm,
        'filter_formset': TahunAjaranSemesterFormset,
    }
    add_more_btn_text = 'Tambah filter'
    
    def get_form_kwargs(self):
        kwargs = super().get_form_kwargs()
        kwargs['kurikulum_form'].update({
            'prodi': self.request.user.prodi,
        })
        kwargs['filter_formset'].update({
            'prefix': self.form_classes['filter_formset'].get_default_prefix()
        })
        return kwargs
        
    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context.update({
            'is_formset_row': True,
            'add_more_btn_text': self.add_more_btn_text,
        })
        
        return context
    
    def show_result_messages(self, is_success: bool, message: str):
        if is_success:
            messages.success(self.request, message)
        else:
            messages.error(self.request, message)


class LaporanCapaianPembelajaranView(LaporanCapaianPembelajaranTemplateView):
    template_name = 'laporan-cpl/home.html'
    success_url = reverse_lazy('laporan_cpl:home')

    def get(self, request: HttpRequest, *args, **kwargs) -> HttpResponse:
        if request.user.role == 'm':
            return redirect(request.user.get_laporan_cpl_url())
        return super().get(request, *args, **kwargs)

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        
        time = timezone.now().strftime('%d%m%Y-%H%M%S')
        raw_cpl_prodi_filename = 'Laporan CPL Prodi RAW-{}.xlsx'.format(time)
        cpl_prodi_filename = 'Laporan CPL Prodi-{}.pdf'.format(time)
        cpl_mahasiswa_filename = 'Laporan CPL Mahasiwa-{}.pdf'.format(time)
        
        context.update({
            'cpl_prodi_filename': cpl_prodi_filename,
            'cpl_mahasiswa_filename': cpl_mahasiswa_filename,
            'raw_cpl_prodi_filename': raw_cpl_prodi_filename,
        })
        
        return context

    def forms_valid(self, forms: dict) -> HttpResponse:
        kurikulum_obj = forms['kurikulum_form'].cleaned_data.get('kurikulum')
        formset_cleaned_data = forms['filter_formset'].cleaned_data

        # Get list ilo and max sks prodi
        list_ilo, max_sks_prodi = get_ilo_and_sks_from_kurikulum(kurikulum_obj)
        
        # Filter dict is based on tahun ajaran
        """
        filter_dict = {
            tahun_ajaran_prodi_id:[
                semester_prodi_id
            ],
        }
        """
        filter_dict = {}

        if len(formset_cleaned_data) == 0:
            is_multiple_result = False
            # Filter by kurikulum
            # Filter peserta MK
            list_peserta_mk = PesertaMataKuliah.objects.filter(
                kelas_mk_semester__mk_semester__mk_kurikulum__kurikulum=kurikulum_obj
            ).exclude(nilai_akhir=None)

            filter = [(kurikulum_obj, kurikulum_obj.nama)]
            
            # Process
            prodi_task = async_task(
                process_ilo_prodi_by_kurikulum,
                list_ilo, max_sks_prodi, filter, is_multiple_result
            )
            mahasiswa_task = async_task(
                process_ilo_mahasiswa_by_kurikulum,
                list_ilo, max_sks_prodi, filter, is_multiple_result, list_peserta_mk
            )
        else:
            # Filter by tahun ajaran or semester
            is_semester_included = len(formset_cleaned_data[0].get('semester', '').strip()) != 0

            # Separate tahun ajaran and semester
            for clean_data in formset_cleaned_data:
                tahun_ajaran_prodi_id = clean_data['tahun_ajaran']

                if tahun_ajaran_prodi_id not in filter_dict.keys():
                    filter_dict[tahun_ajaran_prodi_id] = []
                
                if is_semester_included:
                    semester_prodi_id = clean_data['semester']
                    filter_dict[tahun_ajaran_prodi_id].append(semester_prodi_id)
            
            filter = []
            if is_semester_included:
                # Semester filters
                for tahun_ajaran_prodi_id, list_semester_prodi_id in filter_dict.items():
                    for semester_prodi_id in list_semester_prodi_id:
                        if not semester_prodi_id.strip(): continue

                        try:
                            semester_prodi_obj = SemesterProdi.objects.get(
                                id_neosia=semester_prodi_id
                            )
                        except SemesterProdi.DoesNotExist:
                            message = 'Semester Prodi (ID={}) tidak ada di database.'.format(semester_prodi_id)
                            if settings.DEBUG: print(message)
                            messages.error(self.request, message)
                            continue
                        except SemesterProdi.MultipleObjectsReturned:
                            message = 'Semester Prodi (ID={}) mengembalikan multiple object.'.format(semester_prodi_id)

templates/laporan-cpl/partials/list-mahasiswa-prodi.html
<a href="javascript:void(0);" id="download-cpl-mahasiswa" data-url="{% url 'laporan_cpl:download' %}?download_cpl=mahasiswa&task_id={{ mahasiswa_task }}" class="btn btn-icon-start btn-success max-w-min" role="menuitem link">
    <svg xmlns="http://www.w3.org/2000/svg" focusable="False" fill="currentColor" class="bi bi-file-earmark-pdf w-4 h-4 fill-slate-100" viewBox="0 0 16 16">
        <path d="M14 14V4.5L9.5 0H4a2 2 0 0 0-2 2v12a2 2 0 0 0 2 2h8a2 2 0 0 0 2-2zM9.5 3A1.5 1.5 0 0 0 11 4.5h2V14a1 1 0 0 1-1 1H4a1 1 0 0 1-1-1V2a1 1 0 0 1 1-1h5.5v2z"/>
        <path d="M4.603 14.087a.81.81 0 0 1-.438-.42c-.195-.388-.13-.776.08-1.102.198-.307.526-.568.897-.787a7.68 7.68 0 0 1 1.482-.645 19.697 19.697 0 0 0 1.062-2.227 7.269 7.269 0 0 1-.43-1.295c-.086-.4-.119-.796-.046-1.136.075-.354.274-.672.65-.823.192-.077.4-.12.602-.077a.7.7 0 0 1 .477.365c.088.164.12.356.127.538.007.188-.012.396-.047.614-.084.51-.27 1.134-.52 1.794a10.954 10.954 0 0 0 .98 1.686 5.753 5.753 0 0 1 1.334.05c.364.066.734.195.96.465.12.144.193.32.2.518.007.192-.047.382-.138.563a1.04 1.04 0 0 1-.354.416.856.856 0 0 1-.51.138c-.331-.014-.654-.196-.933-.417a5.712 5.712 0 0 1-.911-.95 11.651 11.651 0 0 0-1.997.406 11.307 11.307 0 0 1-1.02 1.51c-.292.35-.609.656-.927.787a.793.793 0 0 1-.58.029zm1.379-1.901c-.166.076-.32.156-.459.238-.328.194-.541.383-.647.547-.094.145-.096.25-.04.361.01.022.02.036.026.044a.266.266 0 0 0 .035-.012c.137-.056.355-.235.635-.572a8.18 8.18 0 0 0 .45-.606zm1.64-1.33a12.71 12.71 0 0 1 1.01-.193 11.744 11.744 0 0 1-.51-.858 20.801 20.801 0 0 1-.5 1.05zm2.446.45c.15.163.296.3.435.41.24.19.407.253.498.256a.107.107 0 0 0 .07-.015.307.307 0 0 0 .094-.125.436.436 0 0 0 .059-.2.095.095 0 0 0-.026-.063c-.052-.062-.2-.152-.518-.209a3.876 3.876 0 0 0-.612-.053zM8.078 7.8a6.7 6.7 0 0 0 .2-.828c.031-.188.043-.343.038-.465a.613.613 0 0 0-.032-.198.517.517 0 0 0-.145.04c-.087.035-.158.106-.196.283-.04.192-.03.469.046.822.024.111.054.227.09.346z"/>
    </svg>
    <span>Download laporan CPL semua mahasiswa</span>
</a>

{% if object_list|length > 0 %}
    {% include 'components/list-table-view/model-e/table-view-model-e.html' %}
{% else %}
    <p>Tidak ditemukan data dengan filter yang diberikan</p>
{% endif %}

templates/laporan-cpl/partials/list-pi.html
<a href="javascript:void(0);" id="download-pi" data-url="{% url 'laporan_cpl:download-laporan-pi' %}?download_pi=true&task_id={{ pi_task }}" class="btn btn-icon-start btn-success max-w-min" role="menuitem link">
    <svg xmlns="http://www.w3.org/2000/svg" focusable="False" fill="currentColor" class="bi bi-file-earmark-pdf w-4 h-4 fill-slate-100" viewBox="0 0 16 16">
        <path d="M14 14V4.5L9.5 0H4a2 2 0 0 0-2 2v12a2 2 0 0 0 2 2h8a2 2 0 0 0 2-2zM9.5 3A1.5 1.5 0 0 0 11 4.5h2V14a1 1 0 0 1-1 1H4a1 1 0 0 1-1-1V2a1 1 0 0 1 1-1h5.5v2z"/>
        <path d="M4.603 14.087a.81.81 0 0 1-.438-.42c-.195-.388-.13-.776.08-1.102.198-.307.526-.568.897-.787a7.68 7.68 0 0 1 1.482-.645 19.697 19.697 0 0 0 1.062-2.227 7.269 7.269 0 0 1-.43-1.295c-.086-.4-.119-.796-.046-1.136.075-.354.274-.672.65-.823.192-.077.4-.12.602-.077a.7.7 0 0 1 .477.365c.088.164.12.356.127.538.007.188-.012.396-.047.614-.084.51-.27 1.134-.52 1.794a10.954 10.954 0 0 0 .98 1.686 5.753 5.753 0 0 1 1.334.05c.364.066.734.195.96.465.12.144.193.32.2.518.007.192-.047.382-.138.563a1.04 1.04 0 0 1-.354.416.856.856 0 0 1-.51.138c-.331-.014-.654-.196-.933-.417a5.712 5.712 0 0 1-.911-.95 11.651 11.651 0 0 0-1.997.406 11.307 11.307 0 0 1-1.02 1.51c-.292.35-.609.656-.927.787a.793.793 0 0 1-.58.029zm1.379-1.901c-.166.076-.32.156-.459.238-.328.194-.541.383-.647.547-.094.145-.096.25-.04.361.01.022.02.036.026.044a.266.266 0 0 0 .035-.012c.137-.056.355-.235.635-.572a8.18 8.18 0 0 0 .45-.606zm1.64-1.33a12.71 12.71 0 0 1 1.01-.193 11.744 11.744 0 0 1-.51-.858 20.801 20.801 0 0 1-.5 1.05zm2.446.45c.15.163.296.3.435.41.24.19.407.253.498.256a.107.107 0 0 0 .07-.015.307.307 0 0 0 .094-.125.436.436 0 0 0 .059-.2.095.095 0 0 0-.026-.063c-.052-.062-.2-.152-.518-.209a3.876 3.876 0 0 0-.612-.053zM8.078 7.8a6.7 6.7 0 0 0 .2-.828c.031-.188.043-.343.038-.465a.613.613 0 0 0-.032-.198.517.517 0 0 0-.145.04c-.087.035-.158.106-.196.283-.04.192-.03.469.046.822.024.111.054.227.09.346z"/>
    </svg>
    <span>Download laporan PI</span>
</a>

{% if object_list|length > 0 %}
    {% include 'components/list-table-view/model-e/table-view-model-e.html' %}
{% else %}
    <p>Tidak ditemukan data dengan filter yang diberikan</p>
{% endif %}