clo/urls.py
from django.urls import path
from .views import (
    CloReadAllView,
    CloCreateView,
    CloUpdateView,
    CloBulkDeleteView,
    CloDuplicateView,
    CloReadAllGraphJsonResponse,
    CloReadView,
    CloLockView,
    CloUnlockView,

    KomponenCloBulkDeleteView,
    KomponenCloCreateView,
    KomponenCloGraphJsonResponse,
)


app_name = 'clo'
urlpatterns = [
    path('', CloReadAllView.as_view(), name='read-all'),
    path('<int:clo_id>/', CloReadView.as_view(), name='read'),
    path('<int:clo_id>/update/', CloUpdateView.as_view(), name='update'),
    path('create/', CloCreateView.as_view(), name='create'),
    path('duplicate/', CloDuplicateView.as_view(), name='duplicate'),
    path('bulk-delete/', CloBulkDeleteView.as_view(), name='bulk-delete'),
    path('read-all-graph/', CloReadAllGraphJsonResponse.as_view(), name='read-all-graph'),
    path('lock/', CloLockView.as_view(), name='lock'),
    path('unlock/', CloUnlockView.as_view(), name='unlock'),

    # Komponen CLO
    path('<int:clo_id>/bulk-delete/', KomponenCloBulkDeleteView.as_view(), name='komponen-clo-bulk-delete'),
    path('<int:clo_id>/create/', KomponenCloCreateView.as_view(), name='komponen-clo-create'),
    path('<int:clo_id>/komponen-graph/', KomponenCloGraphJsonResponse.as_view(), name='komponen-clo-graph')
]

learning_outcomes_assessment/urls.py
from django.contrib import admin
from django.urls import path, include, re_path
from .views import (
    home_view, dosen_json_response, get_task_result,
    get_admin_only_view
)
from clo.views import DuplicateCpmkLintasMkView
from django.views.static import serve 
from django.conf import settings


urlpatterns = [
    path('', home_view),
    path('admin/', admin.site.urls),
    path('accounts/', include('accounts.urls')),
    path('kurikulum/', include('kurikulum.urls')),
    path('semester/', include('semester.urls')),
    path('laporan-cpl/', include('laporan_cpl.urls')),
    path('dosen-search/', dosen_json_response, name='dosen-search'),
    path('task/', get_task_result, name='task-result'),

    # Admin only
    path('admin-only/', get_admin_only_view, name='admin-only'),
    path('admin-only/duplicate-cpmk-lintas-mk/', DuplicateCpmkLintasMkView.as_view(), name='duplicate-cpmk-lintas-mk'),

    re_path(r'^media/(?P<path>.*)$', serve,{'document_root': settings.MEDIA_ROOT}), 
    re_path(r'^static/(?P<path>.*)$', serve,{'document_root': settings.STATIC_ROOT}), 
]

semester/urls.py
from django.urls import path, include
from .views import(
    SemesterReadAllView,
    SemesterReadView,
    SemesterCreateView,
    SemesterBulkUpdateView,
    SemesterBulkDeleteView,
)


app_name = 'semester'
urlpatterns = [
    path('', SemesterReadAllView.as_view(), name='read-all'),
    path('delete/', SemesterBulkDeleteView.as_view(), name='bulk-delete'),
    path('create/', SemesterCreateView.as_view(), name='create'),
    path('bulk-update/', SemesterBulkUpdateView.as_view(), name='bulk-update'),
    path('<int:semester_prodi_id>/', SemesterReadView.as_view(), name='read'),

    # MK Semester
    path('<int:semester_prodi_id>/mk/', include('mata_kuliah_semester.urls')),
]

semester/forms.py
from django import forms
from django.conf import settings

from semester.models import SemesterProdi
from .utils import (
    get_semester_prodi_choices,
)
from mata_kuliah_semester.utils import(
    get_kelas_mk_semester,
)
from learning_outcomes_assessment.widgets import (
    ChoiceListInteractiveModelA, 
    UpdateChoiceList,
)


class SemesterProdiCreateForm(forms.Form):
    semester_from_neosia = forms.MultipleChoiceField(
        widget=ChoiceListInteractiveModelA(
            badge_template='semester/partials/badge-list-semester-prodi.html',
            list_custom_field_template='semester/partials/list-custom-field-semester-prodi.html',
            table_custom_field_template='semester/partials/table-custom-field-semester-prodi.html',
            table_custom_field_header_template='semester/partials/table-custom-field-header-semester-prodi.html',
        ),
        label = 'Tambahkan Semester dari Neosia',
        help_text = 'Data di bawah ini merupakan data baru dari Neosia dan belum ditemukan dalam database. Beri centang pada item yang ingin anda tambahkan.<br>Note: Data semester yang tidak bisa dicentang berarti semester tidak memiliki data mata kuliah di Neosia atau semester sudah disinkronisasi.',
        required = False,
    )

    def __init__(self, *args, **kwargs):
        prodi_jenjang_id = kwargs.pop('prodi_jenjang_id')
        super().__init__(*args, **kwargs)
        self.label_suffix = ""

        semester_prodi_choices = get_semester_prodi_choices(prodi_jenjang_id)

        for semester_prodi_id, _ in semester_prodi_choices:
            # Check semester prodi in database
            semester_prodi_qs = SemesterProdi.objects.filter(
                id_neosia=semester_prodi_id
            )
            if semester_prodi_qs.exists(): 
                # Set input with semester that has already been in database to false
                self.fields.get('semester_from_neosia').widget.condition_dict.update({
                    semester_prodi_id: False
                })

            kelas_mk_semester = get_kelas_mk_semester(semester_prodi_id)

            if len(kelas_mk_semester) == 0: 
                # Set input with semester that has no MK Semester to false
                self.fields.get('semester_from_neosia').widget.condition_dict.update({
                    semester_prodi_id: False
                })

        self.fields['semester_from_neosia'].choices = semester_prodi_choices

    def clean(self):
        cleaned_data = super().clean()
        if len(self.fields['semester_from_neosia'].choices) == 0: return cleaned_data

        # Clean kurikulum IDs
        semester_from_neosia = cleaned_data.get('semester_from_neosia')
        semester_from_neosia = [*set(semester_from_neosia)]
        cleaned_data['semester_from_neosia'] = semester_from_neosia

        is_semester_valid = len(semester_from_neosia) > 0

        if not is_semester_valid:
            self.add_error('semester_from_neosia', 'Pilih minimal 1 (satu) semester')

        if settings.DEBUG: print("Clean data: {}".format(cleaned_data))
        
        return cleaned_data


class SemesterProdiBulkUpdateForm(forms.Form):
    update_data_semester = forms.MultipleChoiceField(
        widget=UpdateChoiceList(
            badge_template='semester/partials/badge-list-semester-prodi.html',
            list_custom_field_template='semester/partials/list-custom-field-semester-prodi.html',
            list_item_name='semester/partials/list-item-name-semester-prodi.html',
        ),
        label = 'Update Data Semester',
        help_text = 'Data yang berwarna hijau merupakan data terbaru dari Neosia.<br>Data yang berwarna merah merupakan data lama pada sistem ini.<br>Beri centang pada item yang ingin anda update.',
        required = False,
    )

semester/views.py
from django.conf import settings
from django.http import HttpRequest, HttpResponse
from django.core.exceptions import PermissionDenied
from django.contrib import messages
from django.contrib.auth.mixins import PermissionRequiredMixin
from django.shortcuts import redirect
from django.urls import reverse_lazy
from learning_outcomes_assessment.wizard.views import MySessionWizardView
from learning_outcomes_assessment.forms.edit import (
    ModelBulkDeleteView,
    ModelBulkUpdateView
)
from learning_outcomes_assessment.list_view.views import (
    ListViewModelA,
    DetailWithListViewModelA,
)
from learning_outcomes_assessment.auth.mixins import ProgramStudiMixin
from accounts.forms import ProgramStudiJenjangSelectForm
from mata_kuliah_semester.filters import MataKuliahSemesterFilter, MataKuliahSemesterSort
from mata_kuliah_semester.models import MataKuliahSemester
from .filters import(
    SemesterProdiFilter,
    SemesterProdiSort
)
from .forms import(
    SemesterProdiCreateForm,
    SemesterProdiBulkUpdateForm,
)
from accounts.models import ProgramStudiJenjang
from .models import(
    TahunAjaran,
    TahunAjaranProdi,
    TipeSemester,
    Semester, 
    SemesterProdi,
)
from .utils import(
    get_semester_prodi,
    get_update_semester_prodi_choices
)


# Create your views here.
class SemesterReadAllView(PermissionRequiredMixin, ListViewModelA):
    permission_required = (
        'semester.view_semester', 
        'semester.view_semesterprodi', 
        'semester.view_tahunajaran', 
        'semester.view_tahunajaranprodi',
    )
    model = SemesterProdi
    paginate_by: int = 10
    template_name: str = 'semester/home.html'
    ordering: str = ['tahun_ajaran_prodi__prodi_jenjang__jenjang_studi__kode', '-semester__tahun_ajaran', '-semester__tipe_semester']
    sort_form_ordering_by_key: str = 'ordering_by'

    semester_filter: SemesterProdiFilter = None
    semester_sort: SemesterProdiSort = None

    bulk_delete_url: str = reverse_lazy('semester:bulk-delete')
    reset_url: str = reverse_lazy('semester:read-all')
    list_id: str = 'semester-list-content'
    input_name: str = 'id_semester'
    list_prefix_id: str = 'semester-'
    list_item_name: str = 'semester/partials/list-item-name-semester-prodi.html'
    badge_template: str = 'semester/partials/badge-list-semester-prodi.html'
    list_custom_field_template: str = 'semester/partials/list-custom-field-semester-prodi.html'
    table_custom_field_header_template: str = 'semester/partials/table-custom-field-header-semester-prodi.html'
    table_custom_field_template: str = 'semester/partials/table-custom-field-semester-prodi.html'
    filter_template: str = 'semester/partials/semester-prodi-filter-form.html'
    sort_template: str = 'semester/partials/semester-prodi-sort-form.html'

    def get(self, request: HttpRequest, *args, **kwargs) -> HttpResponse:
        if request.user.prodi is None: raise PermissionDenied()

        semester_qs = self.get_queryset()

        if semester_qs.exists():
            filter_data = {
                'nama': request.GET.get('nama', ''),
                'tipe_semester': request.GET.get('tipe_semester', ''),
            }
            sort_data = {
                self.sort_form_ordering_by_key: request.GET.getlist(self.sort_form_ordering_by_key, self.ordering)
            }

            self.filter_form = SemesterProdiFilter(
                data=filter_data or None, 
                queryset=semester_qs
            )
            self.sort_form = SemesterProdiSort(
                data=sort_data, 
                initial={self.sort_form_ordering_by_key: self.ordering}
            )

        return super().get(request, *args, **kwargs)

    def get_queryset(self):
        user = self.request.user
        prodi_id = user.prodi.id_neosia
        
        if user.role == 'm':
            self.queryset = self.model.objects.filter(
                matakuliahsemester__kelasmatakuliahsemester__pesertamatakuliah__mahasiswa=user
            ).distinct()
        else:
            self.queryset = self.model.objects.filter(
                tahun_ajaran_prodi__prodi_jenjang__program_studi__id_neosia=prodi_id
            )
        return super().get_queryset()


class SemesterCreateView(PermissionRequiredMixin, MySessionWizardView):
    permission_required = (
        'semester.add_tahunajaran',
        'semester.add_tahunajaranprodi',
        'semester.add_semester',
        'semester.add_semesterprodi',
    )
    form_list = [ProgramStudiJenjangSelectForm, SemesterProdiCreateForm]
    template_name = 'semester/create-view.html'
    success_url = reverse_lazy('semester:read-all')

    def get(self, request, *args, **kwargs):
        if request.user.prodi is None:
            raise PermissionDenied
        return super().get(request, *args, **kwargs)

    def get_form_kwargs(self, step=None):
        form_kwargs = super().get_form_kwargs(step)

        match step:
            case '0':
                form_kwargs.update({'user': self.request.user})
            case '1':
                selected_prodi_jenjang: int = self.get_cleaned_data_for_step('0')['prodi_jenjang']
                form_kwargs.update({
                    'prodi_jenjang_id': selected_prodi_jenjang
                })

        return form_kwargs

    def get_context_data(self, form, **kwargs):
        context = super().get_context_data(form, **kwargs)
        match(self.steps.current):
            case '0':
                context.update({
                    'search_text': False,
                })
            case '1':
                context.update({
                    'search_placeholder': 'Cari nama semester...',
                    'list_item_name': 'semester/partials/list-item-name-semester-prodi.html'
                })
        return context
    
    def done(self, form_list, **kwargs):
        cleaned_data = self.get_all_cleaned_data()

        prodi_jenjang_id = cleaned_data.get('prodi_jenjang')
        list_semester_prodi_id = cleaned_data.get('semester_from_neosia')

        # Get prodi object
        prodi_jenjang_obj: ProgramStudiJenjang = ProgramStudiJenjang.objects.get(id_neosia=prodi_jenjang_id)

        list_semester_prodi = get_semester_prodi(prodi_jenjang_obj.id_neosia)
        
        # Get detail semester prodi from Neosia
        for semester_prodi in list_semester_prodi:
            if str(semester_prodi['id_neosia']) not in list_semester_prodi_id: continue

            # Get or create tahun ajaran
            tahun_ajaran_obj, _ = TahunAjaran.objects.get_or_create_tahun_ajaran(semester_prodi['semester']['tahun_ajaran'])

            # Get or create tahun ajaran prodi
            tahun_ajaran_prodi_obj, _ = TahunAjaranProdi.objects.get_or_create(
                tahun_ajaran=tahun_ajaran_obj,
                prodi_jenjang=prodi_jenjang_obj
            )

            # Get tipe semester
            match(semester_prodi['semester']['tipe_semester']): 
                case 'ganjil':
                    tipe_semester = TipeSemester.GANJIL
                case 'genap':
                    tipe_semester = TipeSemester.GENAP

            # Get or create semester
            semester_obj, _ = Semester.objects.get_or_create(
                id_neosia=semester_prodi['semester']['id_semester'],
                tahun_ajaran=tahun_ajaran_obj,
                nama=semester_prodi['nama'],
                tipe_semester=tipe_semester
            )

            # Create semester prodi
            SemesterProdi.objects.create(
                id_neosia=semester_prodi['id_neosia'],
                tahun_ajaran_prodi=tahun_ajaran_prodi_obj,
                semester=semester_obj
            )

        messages.success(self.request, 'Berhasil menambahkan semester')

        return redirect(self.success_url)


class SemesterBulkUpdateView(PermissionRequiredMixin, ModelBulkUpdateView):
    permission_required = ('semester.change_semester', 'semester.change_semesterprodi',)
    form_class = SemesterProdiBulkUpdateForm
    template_name = 'semester/bulk-update-view.html'
    success_url = reverse_lazy('semester:read-all')

    back_url: str = reverse_lazy('semester:read-all')
    form_field_name: str = 'update_data_semester'
    search_placeholder: str = 'Cari nama semester...'
    no_choices_msg: str = 'Data semester sudah sinkron dengan data di Neosia'

    def setup(self, request: HttpRequest, *args, **kwargs):
        super().setup(request, *args, **kwargs)
        self.choices =  get_update_semester_prodi_choices(request.user.prodi)

    def form_valid(self, form) -> HttpResponse:
        # Get semester prodi ids
        update_semester_data = form.cleaned_data.get(self.form_field_name, [])

        # Update semester
        for update_semester_id, semester_data in self.choices:
            new_semester_data = semester_data['new']
            
            if str(update_semester_id) not in update_semester_data: continue

            # Get semester prodi
            try:
                semester_prodi_obj = SemesterProdi.objects.filter(id_neosia=update_semester_id)
            except SemesterProdi.DoesNotExist:
                messages.error(self.request, 
                    'Gagal mengupdate semester prodi. Error: Semester Prodi dengan ID: {} tidak ditemukan.'.format(update_semester_id))
                continue
            
            # Get tahun ajaran
            tahun_ajaran_obj, _ = TahunAjaran.objects.get_or_create_tahun_ajaran(new_semester_data['semester']['tahun_ajaran'])
            
            # Get tipe semester
            match(new_semester_data['semester']['tipe_semester']):
                case 'ganjil':
                    tipe_semester = TipeSemester.GANJIL
                case 'genap':
                    tipe_semester = TipeSemester.GENAP

            # Get prodi jenjang
            prodi_jenjang_obj: ProgramStudiJenjang = new_semester_data['tahun_ajaran_prodi']['prodi_jenjang']
            
            # Get tahun ajaran prodi

templates/semester/bulk-update-view.html
{% extends 'home-view.html' %}

{% block title %}
Update Semester - 
{% endblock title %}

{% block breadcrumb %}
<li class="breadcrumb-item"><a href="{% url 'semester:read-all' %}" role="listitem">Semester</a></li>
<li class="breadcrumb-item active" aria-current="page" role="listitem">Update Semester</li>
{% endblock breadcrumb %}

{% block content %}
{% include 'components/form/single-form.html' %}
{% endblock content %}

templates/semester/create-view.html
{% extends 'home-view.html' %}

{% block title %}
Tambah Semester - 
{% endblock title %}

{% block breadcrumb %}
<li class="breadcrumb-item"><a href="{% url 'semester:read-all' %}" role="listitem">Semester</a></li>
<li class="breadcrumb-item active" aria-current="page" role="listitem">Tambah Semester</li>
{% endblock breadcrumb %}

{% block content %}
{% include 'components/form/form-wizard-with-list.html' %}
{% endblock content %}

templates/semester/detail-view.html
{% extends 'home-view.html' %}

{% block title %}
{{ single_object.semester.nama }} - 
{% endblock title %}

{% block breadcrumb %}
<li class="breadcrumb-item"><a href="{% url 'semester:read-all' %}" role="listitem">Semester</a></li>
<li class="breadcrumb-item active" aria-current="page" role="listitem">Detail</li>
{% endblock breadcrumb %}

{% block content %}
{% if object_list or data_exist %}
    <div class="h-icon">
        <h1>{{ single_object.semester.nama }}</h1>
        {% if user_role != 'm' %}
        <a href="{{ single_object.get_create_mk_semester_url }}" class="btn btn-success loading-trigger">
            <svg xmlns="http://www.w3.org/2000/svg" focusable="False" role="img" aria-label="" fill="currentColor" class="bi bi-plus" viewBox="0 0 16 16">
                <path d="M8 4a.5.5 0 0 1 .5.5v3h3a.5.5 0 0 1 0 1h-3v3a.5.5 0 0 1-1 0v-3h-3a.5.5 0 0 1 0-1h3v-3A.5.5 0 0 1 8 4z"/>
            </svg>
            <span class="hidden sm:block">Tambah</span>
        </a>
        {% endif %}
    </div>

    {% include 'components/list-table-view/list-tools.html' with search_field=filter_form.nama %}

    {% if object_list %}
        {% include 'components/list-table-view/model-a/read-all-view.html' %}
    {% else %}
        <p>Tidak ditemukan data dengan filter yang diberikan</p>
    {% endif %}
{% else %}
    <h1>{{ single_object.semester.nama }}</h1>
    {% if user_role == 'm' %}
    <p>Data mata kuliah semester belum ada.</p>
    {% else %}
    <a href="{{ single_object.get_create_mk_semester_url }}" class="btn btn-primary btn-icon-start max-w-min loading-trigger">
        <svg xmlns="http://www.w3.org/2000/svg" focusable="False" role="img" aria-label="" fill="currentColor" class="bi bi-plus" viewBox="0 0 16 16">
            <path d="M8 4a.5.5 0 0 1 .5.5v3h3a.5.5 0 0 1 0 1h-3v3a.5.5 0 0 1-1 0v-3h-3a.5.5 0 0 1 0-1h3v-3A.5.5 0 0 1 8 4z"/>
        </svg>
        Sinkronisasi data mata kuliah semester dengan Neosia
    </a>
    {% endif %}
{% endif %}

{% endblock content %}

templates/semester/home.html
{% extends 'home-view.html' %}

{% block title %}
Semester - 
{% endblock title %}

{% block breadcrumb %}
<li class="breadcrumb-item active" aria-current="page" role="listitem">Semester</li>
{% endblock breadcrumb %}

{% block content %}
{% if object_list or data_exist %}
    <div class="h-icon">
        <h1>Data Semester</h1>
        
        {% if user_role == 'a' %}
        <a href="{% url 'semester:create' %}" title="Tambah data semester" type="button" class="btn btn-success">
            <svg xmlns="http://www.w3.org/2000/svg" focusable="False" role="img" aria-label="" fill="currentColor" class="bi bi-plus" viewBox="0 0 16 16">
                <path d="M8 4a.5.5 0 0 1 .5.5v3h3a.5.5 0 0 1 0 1h-3v3a.5.5 0 0 1-1 0v-3h-3a.5.5 0 0 1 0-1h3v-3A.5.5 0 0 1 8 4z"/>
            </svg>
            <span class="hidden sm:block">Tambah</span>
        </a>
        <a href="{% url 'semester:bulk-update' %}" title="Update data semester" type="button" class="btn btn-primary">
            <svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 24 24" focusable="False" aria-label="sync">
                <path d="M.01 0h24v24h-24V0z" fill="none"/>
                <path d="M12 4V2.21c0-.45-.54-.67-.85-.35l-2.8 2.79c-.2.2-.2.51 0 .71l2.79 2.79c.32.31.86.09.86-.36V6c3.31 0 6 2.69 6 6 0 .79-.15 1.56-.44 2.25-.15.36-.04.77.23 1.04.51.51 1.37.33 1.64-.34.37-.91.57-1.91.57-2.95 0-4.42-3.58-8-8-8zm0 14c-3.31 0-6-2.69-6-6 0-.79.15-1.56.44-2.25.15-.36.04-.77-.23-1.04-.51-.51-1.37-.33-1.64.34C4.2 9.96 4 10.96 4 12c0 4.42 3.58 8 8 8v1.79c0 .45.54.67.85.35l2.79-2.79c.2-.2.2-.51 0-.71l-2.79-2.79c-.31-.31-.85-.09-.85.36V18z"/>
            </svg>
            <span class="hidden sm:block">Update</span>
        </a>
        {% endif %}
    </div>
    
    {% include 'components/list-table-view/list-tools.html' with search_field=filter_form.nama ordering_by_field=sort_form.ordering_by %}

    {% if object_list %}
        {% include 'components/list-table-view/model-a/read-all-view.html' %}
    {% else %}
        <p>Tidak ditemukan data dengan filter yang diberikan</p>
    {% endif %}
{% else %}
    <h1>Data Semester</h1>
    {% if user_role == 'a' %}
    <a href="{% url 'semester:create' %}" type="button" class="btn btn-primary btn-icon-start max-w-min loading-trigger">
        <svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 24 24" focusable="False" aria-label="sync">
            <path d="M.01 0h24v24h-24V0z" fill="none"/>
            <path d="M12 4V2.21c0-.45-.54-.67-.85-.35l-2.8 2.79c-.2.2-.2.51 0 .71l2.79 2.79c.32.31.86.09.86-.36V6c3.31 0 6 2.69 6 6 0 .79-.15 1.56-.44 2.25-.15.36-.04.77.23 1.04.51.51 1.37.33 1.64-.34.37-.91.57-1.91.57-2.95 0-4.42-3.58-8-8-8zm0 14c-3.31 0-6-2.69-6-6 0-.79.15-1.56.44-2.25.15-.36.04-.77-.23-1.04-.51-.51-1.37-.33-1.64.34C4.2 9.96 4 10.96 4 12c0 4.42 3.58 8 8 8v1.79c0 .45.54.67.85.35l2.79-2.79c.2-.2.2-.51 0-.71l-2.79-2.79c-.31-.31-.85-.09-.85.36V18z"/>
        </svg>
        Sinkronisasi data semester dengan Neosia
    </a>
    {% else %}
    <p>Data semester belum ada.</p>
    {% endif %}
{% endif %}
{% endblock content %}