clo/urls.py
from django.urls import path
from .views import (
    CloReadAllView,
    CloCreateView,
    CloUpdateView,
    CloBulkDeleteView,
    CloDuplicateView,
    CloReadAllGraphJsonResponse,
    CloReadView,
    CloLockView,
    CloUnlockView,

    KomponenCloBulkDeleteView,
    KomponenCloCreateView,
    KomponenCloGraphJsonResponse,
)


app_name = 'clo'
urlpatterns = [
    path('', CloReadAllView.as_view(), name='read-all'),
    path('<int:clo_id>/', CloReadView.as_view(), name='read'),
    path('<int:clo_id>/update/', CloUpdateView.as_view(), name='update'),
    path('create/', CloCreateView.as_view(), name='create'),
    path('duplicate/', CloDuplicateView.as_view(), name='duplicate'),
    path('bulk-delete/', CloBulkDeleteView.as_view(), name='bulk-delete'),
    path('read-all-graph/', CloReadAllGraphJsonResponse.as_view(), name='read-all-graph'),
    path('lock/', CloLockView.as_view(), name='lock'),
    path('unlock/', CloUnlockView.as_view(), name='unlock'),

    # Komponen CLO
    path('<int:clo_id>/bulk-delete/', KomponenCloBulkDeleteView.as_view(), name='komponen-clo-bulk-delete'),
    path('<int:clo_id>/create/', KomponenCloCreateView.as_view(), name='komponen-clo-create'),
    path('<int:clo_id>/komponen-graph/', KomponenCloGraphJsonResponse.as_view(), name='komponen-clo-graph')
]

kurikulum/urls.py
from django.urls import path, include
from .views import (
    KurikulumCreateFormWizardView,
    KurikulumReadAllView,
    KurikulumReadView,
    KurikulumBulkUpdateView,
    KurikulumBulkDeleteView,
)


app_name = 'kurikulum'
urlpatterns = [
    path('', KurikulumReadAllView.as_view(), name='read-all'),
    path('create/', KurikulumCreateFormWizardView.as_view(), name='create'),
    path('delete/', KurikulumBulkDeleteView.as_view(), name='bulk-delete'),
    path('update/', KurikulumBulkUpdateView.as_view(), name='bulk-update'),
    path('<int:kurikulum_id>/', KurikulumReadView.as_view(), name='read'),

    # Mata Kuliah Kurikulum
    path('<int:kurikulum_id>/mk/', include('mata_kuliah_kurikulum.urls')),
    # ILO
    path('<int:kurikulum_id>/cpl/', include('ilo.urls')),
    # Performance Indicator
    path('<int:kurikulum_id>/pi-area/', include('pi_area.urls')),
]

learning_outcomes_assessment/urls.py
from django.contrib import admin
from django.urls import path, include, re_path
from .views import (
    home_view, dosen_json_response, get_task_result,
    get_admin_only_view
)
from clo.views import DuplicateCpmkLintasMkView
from django.views.static import serve 
from django.conf import settings


urlpatterns = [
    path('', home_view),
    path('admin/', admin.site.urls),
    path('accounts/', include('accounts.urls')),
    path('kurikulum/', include('kurikulum.urls')),
    path('semester/', include('semester.urls')),
    path('laporan-cpl/', include('laporan_cpl.urls')),
    path('dosen-search/', dosen_json_response, name='dosen-search'),
    path('task/', get_task_result, name='task-result'),

    # Admin only
    path('admin-only/', get_admin_only_view, name='admin-only'),
    path('admin-only/duplicate-cpmk-lintas-mk/', DuplicateCpmkLintasMkView.as_view(), name='duplicate-cpmk-lintas-mk'),

    re_path(r'^media/(?P<path>.*)$', serve,{'document_root': settings.MEDIA_ROOT}), 
    re_path(r'^static/(?P<path>.*)$', serve,{'document_root': settings.STATIC_ROOT}), 
]

mata_kuliah/urls.py
from django.urls import path
from .views import (
    MataKuliahSemesterReadAllHxView,
    MataKuliahSemesterCreateView,
    MataKuliahSemesterUpdateView,
    MataKuliahSemesterReadView,
)


app_name = 'mata_kuliah'
urlpatterns = [
    path('hx/', MataKuliahSemesterReadAllHxView.as_view(), name='hx-read-all'),
    path('<int:mk_semester_id>/', MataKuliahSemesterReadView.as_view(), name='read'),
    path('create/', MataKuliahSemesterCreateView.as_view(), name='create'),
    path('update/', MataKuliahSemesterUpdateView.as_view(), name='update'),
]

semester/urls.py
from django.urls import path, include
from .views import(
    SemesterReadAllView,
    SemesterReadView,
    SemesterCreateView,
    SemesterBulkUpdateView,
    SemesterBulkDeleteView,
)


app_name = 'semester'
urlpatterns = [
    path('', SemesterReadAllView.as_view(), name='read-all'),
    path('delete/', SemesterBulkDeleteView.as_view(), name='bulk-delete'),
    path('create/', SemesterCreateView.as_view(), name='create'),
    path('bulk-update/', SemesterBulkUpdateView.as_view(), name='bulk-update'),
    path('<int:semester_prodi_id>/', SemesterReadView.as_view(), name='read'),

    # MK Semester
    path('<int:semester_prodi_id>/mk/', include('mata_kuliah_semester.urls')),
]

mata_kuliah/models.py
from django.db import models
from django.db.models import CheckConstraint, Q
from django.core.validators import MinValueValidator, MaxValueValidator
from django.urls import reverse
from django.conf import settings
from ilo.models import Ilo
from mata_kuliah_kurikulum.models import MataKuliahKurikulum
from semester.models import SemesterProdi

User = settings.AUTH_USER_MODEL

# Create your models here.
class MataKuliahSemester(models.Model):
    mk_kurikulum = models.ForeignKey(MataKuliahKurikulum, on_delete=models.CASCADE)
    semester = models.ForeignKey(SemesterProdi, on_delete=models.CASCADE)

    average_clo_achievement = models.FloatField(null=True, 
        validators=[MinValueValidator(0.0), MaxValueValidator(100.0)])

    class Meta:
        constraints = (
            CheckConstraint(
                check=Q(average_clo_achievement__gte=0.0) & Q(average_clo_achievement__lte=100.0),
                name='average_clo_achievement_range'
            ),
        )

    def read_detail_url(self):
        return reverse('semester:mata_kuliah:read', kwargs={
            'semester_prodi_id': self.semester.pk,
            'mk_semester_id': self.pk
        })


class KelasMataKuliahSemester(models.Model):
    id_neosia = models.BigIntegerField(primary_key=True, null=False, unique=True)
    mk_semester = models.ForeignKey(MataKuliahSemester, on_delete=models.CASCADE)

    nama = models.CharField(max_length=255)
    kelas = models.CharField(max_length=255)


class PesertaMataKuliah(models.Model):
    kelas_mk_semester = models.ForeignKey(KelasMataKuliahSemester, on_delete=models.CASCADE)
    mahasiswa = models.ForeignKey(User, on_delete=models.CASCADE)


class DosenMataKuliah(models.Model):
    kelas_mk_semester = models.ForeignKey(KelasMataKuliahSemester, on_delete=models.CASCADE)
    mahasiswa = models.ForeignKey(User, on_delete=models.CASCADE)


class NilaiMataKuliahMahasiswa(models.Model):
    peserta = models.ForeignKey(PesertaMataKuliah, on_delete=models.CASCADE)
    nilai_akhir = models.FloatField(null=True, 
        validators=[MinValueValidator(0.0), MaxValueValidator(100.0)])
    
    class Meta:
        constraints = (
            CheckConstraint(
                check=Q(nilai_akhir__gte=0.0) & Q(nilai_akhir__lte=100.0),
                name='nilai_akhir_range'
            ),
        ) 


class NilaiMataKuliahIloMahasiswa(models.Model):
    peserta = models.ForeignKey(PesertaMataKuliah, on_delete=models.CASCADE)
    ilo = models.ForeignKey(Ilo, on_delete=models.CASCADE)
    nilai_ilo = models.FloatField(validators=[MinValueValidator(0.0), MaxValueValidator(100.0)])

    class Meta:
        constraints = (
            CheckConstraint(
                check=Q(nilai_ilo__gte=0.0) & Q(nilai_ilo__lte=100.0),
                name='nilai_ilo_range'
            ),
        ) 

templates/mata-kuliah/mk-kurikulum-create-view.html
{% extends 'home-view.html' %}

{% block title %}
Tambah Mata Kuliah - 
{% endblock title %}

{% block breadcrumb %}
<li class="breadcrumb-item"><a href="{% url 'kurikulum:read-all' %}" role="listitem">Kurikulum</a></li>
<li class="breadcrumb-item"><a href="{{ kurikulum_obj.read_detail_url }}" role="listitem">Detail</a></li>
<li class="breadcrumb-item active" aria-current="page" role="listitem">Tambah mata kuliah</li>
{% endblock breadcrumb %}

{% block content %}
{% include 'components/form/single-form.html' with search_placeholder='Cari nama mata kuliah...' submit_text='Tambahkan' %}
{% endblock %}

templates/mata-kuliah/mk-kurikulum-detail-view.html
{% extends 'home-view.html' %}

{% block title %}
{{ object.nama }} - 
{% endblock title %}

{% block breadcrumb %}
<li class="breadcrumb-item"><a href="{% url 'kurikulum:read-all' %}" role="listitem">Kurikulum</a></li>
<li class="breadcrumb-item"><a href="{{ object.read_kurikulum_url }}" role="listitem">Detail</a></li>
<li class="breadcrumb-item active" aria-current="page" role="listitem">Detail MK</li>
{% endblock breadcrumb %}

{% block content %}
<h1>{{ object.nama }}</h1>

<div class="table-div">
    <div class="tr-div">
        <div class="w-20 sm:w-32 md:w-40 xl:w-48">Kurikulum</div>
        <div>:</div>
        <div>{{ object.kurikulum }}</div>
    </div>
    <div class="tr-div">
        <div class="w-20 sm:w-32 md:w-40 xl:w-48">Kode</div>
        <div>:</div>
        <div>{{ object.kode }}</div>
    </div>
    <div class="tr-div">
        <div class="w-20 sm:w-32 md:w-40 xl:w-48">SKS</div>
        <div>:</div>
        <div>{{ object.sks }}</div>
    </div>
</div>
{% endblock content %}

templates/mata-kuliah/mk-kurikulum-update-view.html
{% extends 'home-view.html' %}

{% block title %}
Update Mata Kuliah - 
{% endblock title %}

{% block breadcrumb %}
<li class="breadcrumb-item"><a href="{% url 'kurikulum:read-all' %}" role="listitem">Kurikulum</a></li>
<li class="breadcrumb-item"><a href="{{ kurikulum_obj.read_detail_url }}" role="listitem">Detail</a></li>
<li class="breadcrumb-item active" aria-current="page" role="listitem">Update mata kuliah</li>
{% endblock breadcrumb %}

{% block content %}
{% include 'components/form/single-form.html' with search_placeholder='Cari nama kurikulum...' submit_text='Update' %}
{% endblock %}

templates/mata-kuliah/mk-semester-create-view.html
{% extends 'home-view.html' %}

{% block title %}
Tambah MK Semester - 
{% endblock title %}

{% block breadcrumb %}
<li class="breadcrumb-item"><a href="{% url 'semester:read-all' %}" role="listitem">Semester</a></li>
<li class="breadcrumb-item"><a href="{{ semester.obj.read_detail_url }}" role="listitem">Detail</a></li>
<li class="breadcrumb-item"><a href="{{ semester_obj.read_all_mk_semester_url }}" role="listitem">MK Semester</a></li>
<li class="breadcrumb-item active" aria-current="page" role="listitem">Tambah MK Semester</li>
{% endblock breadcrumb %}

{% block content %}
{% include 'components/form/single-form.html' with search_placeholder='Cari nama mata kuliah...' %}
{% endblock content %}